FROM arcnor/retro-toolchains-base

ADD buildroot/output/images/opendingux-*.tar.gz /opt/

RUN mv /opt/opendingux-* /opt/opendingux && cd /opt/opendingux && ./relocate-sdk.sh

ENV CROSS_TRIPLE %%CROSS_TRIPLE%%

ENV CROSS_ROOT /opt/opendingux/

ENV SYSROOT ${CROSS_ROOT}/${CROSS_TRIPLE}/sysroot/

ENV PATH ${PATH}:${CROSS_ROOT}/bin:${SYSROOT}/usr/bin

ENV ARCH arm

ENV CROSS_COMPILE ${CROSS_TRIPLE}-

WORKDIR /root
