FROM ghcr.io/arcnor/retro-toolchain/toolchain

ADD buildroot/output/images/opendingux*.tar.gz /opt/

RUN cd /opt/opendingux && ./relocate-sdk.sh

ENV CROSS_TRIPLE %%CROSS_TRIPLE%%

ENV CROSS_ROOT /opt/opendingux/

ENV SYSROOT ${CROSS_ROOT}/${CROSS_TRIPLE}/sysroot/

ENV PATH ${PATH}:${CROSS_ROOT}/bin:${SYSROOT}/usr/bin

ENV ARCH arm

ENV CROSS_COMPILE ${CROSS_TRIPLE}-

ENV CMAKE_TOOLCHAIN_FILE ${CROSS_ROOT}/share/buildroot/toolchainfile.cmake

WORKDIR /root
